### ISSUE TITLE
Alcatraz Compatibility

### ISSUE THREAD

**Issue by lfarah** [hungri-yeti/xSendIssue#2]
Alcatraz Package Manager is makes it really easy for developers to install Xcode Plugins.
It is also really easy to make your awesome plugin available there.
[Check this out](https://github.com/alcatraz/alcatraz-packages)

**Comment by hungri-yeti** [comment]
Absolutely. That was taken care of yesterday https://github.com/alcatraz/alcatraz-packages/pull/477

**Comment by lfarah** [comment]
Awesome, glad to know. I added your lib on [Awesome-iOS](https://github.com/vsouza/awesome-ios), so let's see if you get more users now! Really cool Plugin!

**Comment by hungri-yeti** [comment]
Thank you, hope you find it useful.
